### ISSUE TITLE
Number reverse Problem Solution

### ISSUE THREAD

**Issue by sujith3179** [pankajkompella/Hackerrank-SI-Basic#2]
The solution for Number reverse problem is failing few test cases (Giving wrong answer) @pankajkompella

**Comment by pankajkompella** [comment]
Is it the C code or Python code that's erroneous?

**Comment by sujith3179** [comment]
I think both the codes are not passing all test cases

**Comment by sujith3179** [comment]
The negative numbers are not handled. Check out my python solution for reference. 

Code :
n = int(input())
def reverse(n):
    rev = 0
    while(n > 0):  
        a = n % 10
        rev = rev * 10 + a
        n = n // 10
    return rev 
if n >=0:
    print(reverse(n))
else:
    reverse_num = reverse(n*(-1))
    print(-reverse_num)
